# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termlife < Formula
  desc "Terminal-based Game of Life implementation"
  homepage "https://github.com/ticktockbent/termlife"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ticktockbent/termlife/releases/download/v0.2.0/termlife_0.2.0_darwin_amd64.tar.gz"
      sha256 "067045cf72501635f55c0b3f976592d828f6f3893c77310b4f7114a265b64b46"

      define_method(:install) do
        bin.install "termlife"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ticktockbent/termlife/releases/download/v0.2.0/termlife_0.2.0_darwin_arm64.tar.gz"
      sha256 "6aa8fcd6f59929aa843bf138c069b2c6f31a0279b1070ef97c2fc82bcaa6acbc"

      define_method(:install) do
        bin.install "termlife"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ticktockbent/termlife/releases/download/v0.2.0/termlife_0.2.0_linux_amd64.tar.gz"
      sha256 "1c8b2d5a8bfe320937265c2413af284160d7e02165ec949cd6ffe6fe104e94c3"
      define_method(:install) do
        bin.install "termlife"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ticktockbent/termlife/releases/download/v0.2.0/termlife_0.2.0_linux_arm64.tar.gz"
      sha256 "95ca26fd97643196a3326c6bed875be6372bc0b6053b461212b647a01fe118d9"
      define_method(:install) do
        bin.install "termlife"
      end
    end
  end

  test do
    system "#{bin}/termlife", "--version"
  end
end
